"""Central configuration values for the DHTOL analyzer."""

# Temperature glitch detection
TEMP_PHYS_MIN_C = -10.0
TEMP_PHYS_MAX_C = 250.0
TEMP_MIN_PLAUSIBLE_DELTA_C = 40.0
TEMP_MAX_DTDT_C_PER_S = 20.0
TEMP_DEAD_SENSOR_WINDOW_S = 30.0
TEMP_INSTABILITY_RANGE_C = 5.0
TEMP_INSTABILITY_EFFICIENCY_MAX = 0.25
TEMP_INSTABILITY_DIRECTION_CHANGE_MIN = 0.40
MAX_GLITCH_EVENTS_PER_SENSOR = 1000

# Current-drop attribution
CURRENT_DROP_THRESHOLD_A = 1.0
CURRENT_DROP_CONFIRM_SAMPLES = 2
CURRENT_MATCH_TOLERANCE_A = 0.3
TIME_CORRELATION_WINDOW_S = 2.0

# Fault-event grouping
BOARD_FAULT_SUMMARY_WINDOW_S = 120.0
FAULT_SOURCE_MERGE_TOLERANCE_S = 2.0

# Hardware limits
BOARDS_PER_ZONE = 8
MAX_ZONES = 3
MAX_TOTAL_BOARDS = BOARDS_PER_ZONE * MAX_ZONES

# TDMS timestamps are stored as UTC while text logs use local lab time.
LOCAL_TIMEZONE = "Europe/Vienna"

# Current system assumption
BOARD_CAN_RECONNECT = True
